volumes:
  postgres:

services: 
  postgres:
    container_name: "rk3"
    image: postgres:14
    environment:
      POSTGRES_DB: "rk3"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres
    volumes:
      - /Users/walhay/Study/DB/Rk3/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
        - mynetwork
networks:
  mynetwork:
    driver: bridge
