plugins {
    id 'java'
    id 'application'
}

group = 'com.walhay'
version = '1.0.0'
sourceCompatibility = '21'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.hibernate.orm:hibernate-core:6.4.0.Final'
    implementation 'org.postgresql:postgresql:42.7.3'

    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.walhay.Main'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}
